windows:
  tags:
    - docker
  image:
    name: tshirtman/kpmwine
    entrypoint: [""]
  script:
    - git describe --tag > packaging/version.txt
    - /entrypoint.sh python -m pip install -r packaging/requirements_moving.txt
    - python -m pip install -r packaging/requirements_windows.txt

    - git clean -dfx src
    - git checkout src
    - python packaging/setup.py build_ext --inplace
    - pyinstaller packaging/project.spec --clean -y
    - wine 'C:\Program Files (x86)\Inno Setup 5\ISCC.exe' packaging/project.iss

  artifacts:
    paths:
      - dist/*.exe